# Generated by Django 5.1.6 on 2025-03-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='tamaño',
            field=models.CharField(choices=[('personal', 'Personal'), ('mediana', 'Mediana'), ('grande', 'Grande')], default='personal', max_length=10),
        ),
    ]
