# Generated by Django 5.1.6 on 2025-03-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_detallepedido_tamaño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='tamaño',
            new_name='tamano',
        ),
    ]
