# Generated by Django 5.1.6 on 2025-03-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada')], default='disponible', max_length=20),
        ),
    ]
