# Generated by Django 5.1.6 on 2025-03-04 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio_personal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precio_mediana', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('precio_grande', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='menu.categoria')),
            ],
        ),
    ]
